### ISSUE TITLE
Variants limited to e.g. NSG cards only / Standard legal cards

### ISSUE THREAD

**Issue by cmur2** [lostgeek/gordianbla_v1#1]
I'm relatively new to Netrunner and don't know many of the old FFG cards. If I understand the help text correctly any card ever printed by FFG and NISEI can appear which is a bit overwhelming...

I'd like to make gordianbla.de my daily routine but going from 0 to "all cards ever" is a lot. I thought maybe offering variants limited to certain subsets of cards could make sense. Just wanting to test the waters here, I could probably implement it myself with some pointers on how the generator/PHP works.

**Comment by lostgeek** [comment]
That's a good idea. I'm looking into doing a rewrite of this project after Worlds (as it was hacked together over a weekend or two and deserves a bit of clean up) and I'll add such a mode to it when I do so.
