### ISSUE TITLE
Tree line doesn't register as a Barrier?

### ISSUE THREAD

**Issue by Veronica-212** [lostgeek/gordianbla_v1#3]
While doing today's guessing game, I tried Tree Line, which resulted in matching subtypes. 
However, the card was Curtain Wall. Which is a Barrier? So it should have been half a matching type, right?
![Screenshot_20231103_071414_Firefox](https://github.com/lostgeek/gordianbla/assets/55791889/37ce4b29-c84f-4797-b90e-20a27e827ae8)

**Comment by lostgeek** [comment]
Fixed in the rewrite!
